export const MOCK_FLASHCARDS = {
  photosynthesis: [
    { id: 1, front: 'What is photosynthesis?', back: 'The process by which green plants convert sunlight, water, and CO₂ into glucose and oxygen.' },
    { id: 2, front: 'Where does photosynthesis occur?', back: 'In the chloroplasts of plant cells, specifically in the thylakoid membranes and stroma.' },
    { id: 3, front: 'What is the chemical equation for photosynthesis?', back: '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂' },
    { id: 4, front: 'What pigment absorbs sunlight?', back: 'Chlorophyll — primarily chlorophyll a and chlorophyll b, which absorb red and blue light.' },
    { id: 5, front: 'What are the two main stages?', back: 'Light-dependent reactions (in thylakoids) and the Calvin cycle / light-independent reactions (in stroma).' },
    { id: 6, front: 'What is the role of water in photosynthesis?', back: 'Water is split during the light reactions (photolysis), providing electrons and hydrogen ions. Oxygen is released as a byproduct.' },
    { id: 7, front: 'What is the Calvin Cycle?', back: 'A series of reactions that use CO₂ and ATP/NADPH from light reactions to synthesize G3P, which is used to make glucose.' },
    { id: 8, front: 'What factors affect the rate of photosynthesis?', back: 'Light intensity, CO₂ concentration, temperature, and water availability.' },
    { id: 9, front: 'What is photorespiration?', back: 'A process where RuBisCO fixes O₂ instead of CO₂, reducing photosynthetic efficiency. Common in hot, dry conditions.' },
    { id: 10, front: 'How do C4 plants differ from C3 plants?', back: 'C4 plants use a preliminary carbon fixation step (PEP carboxylase) to concentrate CO₂, reducing photorespiration.' },
  ],
};

export const MOCK_HISTORY = [
  {
    id: 1,
    topic: 'Photosynthesis',
    cardCount: 10,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    cards: MOCK_FLASHCARDS.photosynthesis,
  },
  {
    id: 2,
    topic: 'JavaScript Async/Await',
    cardCount: 8,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    cards: [],
  },
  {
    id: 3,
    topic: 'French Revolution Key Events',
    cardCount: 15,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    cards: [],
  },
  {
    id: 4,
    topic: 'Organic Chemistry — Functional Groups',
    cardCount: 12,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    cards: [],
  },
];

export function generateMockCards(topic, count = 10) {
  if (topic.toLowerCase().includes('photosynthesis')) {
    return MOCK_FLASHCARDS.photosynthesis.slice(0, count);
  }

  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    front: `Question ${i + 1} about "${topic}"`,
    back: `This is the detailed answer for question ${i + 1} about "${topic}". In a real app, this would be generated by an AI model with rich, accurate content.`,
  }));
}